name: test_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1


environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  video_player_media_kit: ^1.0.5
  media_kit_libs_android_video: any
  equatable: ^2.0.5
  video_player: ^2.8.2
  media_kit: ^1.1.10                             # Primary package.
  media_kit_video: ^1.2.4                        # For video rendering.
  media_kit_libs_video: ^1.0.4



dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: 'launcher_icon'
  image_path: "assets/NASA_logoResized.png"

flutter:
  assets:
    - assets/


  uses-material-design: true


